export const METHODS = Object.freeze({
    vaultsList: "vaults.list",
    vaultsCreate: "vaults.create",
    vaultsOpen: "vaults.open",
    vaultsClose: "vaults.close",
    vaultsSummary: "vaults.summary",
    identifiersList: "identifiers.list",
    identifiersGet: "identifiers.get",
    identifiersCreate: "identifiers.create",
    remotesList: "remotes.list",
    remotesGet: "remotes.get",
    remotesResolveOobi: "remotes.resolveOobi",
    remotesUpdate: "remotes.update",
    settingsGet: "settings.get",
    kfBootstrapGet: "kf.bootstrap.get",
    kfOnboardingStart: "kf.onboarding.start",
    kfAccountWitnessesList: "kf.account.witnesses.list",
    kfAccountWatchersList: "kf.account.watchers.list",
    kfAccountWatchersStatus: "kf.account.watchers.status",
    kfAccountWatchersQuery: "kf.account.watchers.query",
    kfServicesOverview: "kf.services.overview",
} as const);