# -*- encoding: utf-8 -*-
"""
keri.core Package
"""

import importlib


_MODULES = {
}


_EXPORTS = {
    "ACastDom": (".structing", "ACastDom"),
    "AClanDom": (".structing", "AClanDom"),
    "Aggor": (".mapping", "Aggor"),
    "AllCastDom": (".structing", "AllCastDom"),
    "AllClanDom": (".structing", "AllClanDom"),
    "AuthTypes": (".kraming", "AuthTypes"),
    "BSCastDom": (".structing", "BSCastDom"),
    "BSClanDom": (".structing", "BSClanDom"),
    "BUDex_1_0": (".counting", "BUDex_1_0"),
    "BUDex_2_0": (".counting", "BUDex_2_0"),
    "BexDex": (".coring", "BexDex"),
    "Bexter": (".coring", "Bexter"),
    "BlindState": (".structing", "BlindState"),
    "BlindStateCastDom": (".structing", "BlindStateCastDom"),
    "BlindStateClanDom": (".structing", "BlindStateClanDom"),
    "Blinder": (".structing", "Blinder"),
    "BoundState": (".structing", "BoundState"),
    "CacheResolver": (".scheming", "CacheResolver"),
    "Castage": (".structing", "Castage"),
    "CiXDex": (".signing", "CiXDex"),
    "Cigar": (".coring", "Cigar"),
    "Cipher": (".signing", "Cipher"),
    "Cizage": (".counting", "Cizage"),
    "ClanToCodens": (".structing", "ClanToCodens"),
    "CodeNames": (".counting", "CodeNames"),
    "CodenToClans": (".structing", "CodenToClans"),
    "Codenage": (".counting", "Codenage"),
    "Codens": (".counting", "Codens"),
    "Compactor": (".mapping", "Compactor"),
    "Counter": (".counting", "Counter"),
    "CtrDex_1_0": (".counting", "CtrDex_1_0"),
    "CtrDex_2_0": (".counting", "CtrDex_2_0"),
    "Dater": (".coring", "Dater"),
    "DecDex": (".coring", "DecDex"),
    "Decimer": (".coring", "Decimer"),
    "Decrypter": (".signing", "Decrypter"),
    "Dicter": (".coring", "Dicter"),
    "DigDex": (".coring", "DigDex"),
    "Diger": (".coring", "Diger"),
    "ECastDom": (".structing", "ECastDom"),
    "EClanDom": (".structing", "EClanDom"),
    "EmptyCastDom": (".structing", "EmptyCastDom"),
    "EmptyClanDom": (".structing", "EmptyClanDom"),
    "Encrypter": (".signing", "Encrypter"),
    "EscapeDex": (".mapping", "EscapeDex"),
    "FSCastDom": (".structing", "FSCastDom"),
    "FSClanDom": (".structing", "FSClanDom"),
    "FieldDom": (".serdering", "FieldDom"),
    "FirstSeen": (".structing", "FirstSeen"),
    "FirstSeenCastDom": (".structing", "FirstSeenCastDom"),
    "FirstSeenClanDom": (".structing", "FirstSeenClanDom"),
    "GenDex": (".counting", "GenDex"),
    "IceMapDom": (".coring", "IceMapDom"),
    "IdrDex": (".indexing", "IdrDex"),
    "IdxBthSigDex": (".indexing", "IdxBthSigDex"),
    "IdxCrtSigDex": (".indexing", "IdxCrtSigDex"),
    "IdxSigDex": (".indexing", "IdxSigDex"),
    "Ilker": (".coring", "Ilker"),
    "Indexer": (".indexing", "Indexer"),
    "JSONSchema": (".scheming", "JSONSchema"),
    "Kever": (".eventing", "Kever"),
    "Kevery": (".eventing", "Kevery"),
    "Kramer": (".kraming", "Kramer"),
    "LabelDex": (".coring", "LabelDex"),
    "Labeler": (".coring", "Labeler"),
    "LargeVrzDex": (".coring", "LargeVrzDex"),
    "LastEstLoc": (".eventing", "LastEstLoc"),
    "MUDex_1_0": (".counting", "MUDex_1_0"),
    "MUDex_2_0": (".counting", "MUDex_2_0"),
    "MapDom": (".coring", "MapDom"),
    "Mapper": (".mapping", "Mapper"),
    "Matter": (".coring", "Matter"),
    "Mediar": (".structing", "Mediar"),
    "MtrDex": (".coring", "MtrDex"),
    "NonTransDex": (".coring", "NonTransDex"),
    "NonceDex": (".coring", "NonceDex"),
    "Noncer": (".coring", "Noncer"),
    "NumDex": (".coring", "NumDex"),
    "Number": (".coring", "Number"),
    "Parser": (".parsing", "Parser"),
    "Pather": (".coring", "Pather"),
    "PreDex": (".coring", "PreDex"),
    "PreNonDigDex": (".coring", "PreNonDigDex"),
    "Prefixer": (".coring", "Prefixer"),
    "ProGen": (".counting", "ProGen"),
    "Pruner": (".kraming", "Pruner"),
    "QTDex_1_0": (".counting", "QTDex_1_0"),
    "Revery": (".routing", "Revery"),
    "Route": (".routing", "Route"),
    "Router": (".routing", "Router"),
    "SCastDom": (".structing", "SCastDom"),
    "SClanDom": (".structing", "SClanDom"),
    "SUDex_1_0": (".counting", "SUDex_1_0"),
    "SUDex_2_0": (".counting", "SUDex_2_0"),
    "Sadder": (".coring", "Sadder"),
    "Saider": (".coring", "Saider"),
    "Saids": (".coring", "Saids"),
    "Salter": (".signing", "Salter"),
    "Schemer": (".scheming", "Schemer"),
    "SealBack": (".structing", "SealBack"),
    "SealCastDom": (".structing", "SealCastDom"),
    "SealClanDom": (".structing", "SealClanDom"),
    "SealDex_2_0": (".counting", "SealDex_2_0"),
    "SealDigest": (".structing", "SealDigest"),
    "SealEvent": (".structing", "SealEvent"),
    "SealKind": (".structing", "SealKind"),
    "SealLast": (".structing", "SealLast"),
    "SealRoot": (".structing", "SealRoot"),
    "SealSource": (".structing", "SealSource"),
    "Sealer": (".structing", "Sealer"),
    "Seqner": (".coring", "Seqner"),
    "Serder": (".serdering", "Serder"),
    "SerderACDC": (".serdering", "SerderACDC"),
    "SerderKERI": (".serdering", "SerderKERI"),
    "Serdery": (".serdering", "Serdery"),
    "Siger": (".indexing", "Siger"),
    "Signer": (".signing", "Signer"),
    "Sizage": (".coring", "Sizage"),
    "SmallVrzDex": (".coring", "SmallVrzDex"),
    "StateEstEvent": (".structing", "StateEstEvent"),
    "StateEvent": (".structing", "StateEvent"),
    "Streamer": (".signing", "Streamer"),
    "Structor": (".structing", "Structor"),
    "TMCastDom": (".structing", "TMCastDom"),
    "TMClanDom": (".structing", "TMClanDom"),
    "TagDex": (".coring", "TagDex"),
    "Tagger": (".coring", "Tagger"),
    "TexDex": (".coring", "TexDex"),
    "Texter": (".coring", "Texter"),
    "Tholder": (".coring", "Tholder"),
    "Tiers": (".signing", "Tiers"),
    "TraitDex": (".coring", "TraitDex"),
    "Traitor": (".coring", "Traitor"),
    "TransLastSigs": (".structing", "TransLastSigs"),
    "TransReceipts": (".structing", "TransReceipts"),
    "TransSigs": (".structing", "TransSigs"),
    "TypeMedia": (".structing", "TypeMedia"),
    "TypeMediaCastDom": (".structing", "TypeMediaCastDom"),
    "TypeMediaClanDom": (".structing", "TypeMediaClanDom"),
    "UniDex_1_0": (".counting", "UniDex_1_0"),
    "UniDex_2_0": (".counting", "UniDex_2_0"),
    "Verfer": (".coring", "Verfer"),
    "Versage": (".coring", "Versage"),
    "Verser": (".coring", "Verser"),
    "Xizage": (".indexing", "Xizage"),
    "ample": (".eventing", "ample"),
    "annot": (".annotating", "annot"),
    "bare": (".eventing", "bare"),
    "compile_uri_template": (".routing", "compile_uri_template"),
    "deReceiptCouple": (".eventing", "deReceiptCouple"),
    "deReceiptTriple": (".eventing", "deReceiptTriple"),
    "deSourceCouple": (".eventing", "deSourceCouple"),
    "deTransReceiptQuadruple": (".eventing", "deTransReceiptQuadruple"),
    "deTransReceiptQuintuple": (".eventing", "deTransReceiptQuintuple"),
    "deWitnessCouple": (".eventing", "deWitnessCouple"),
    "delcept": (".eventing", "delcept"),
    "deltate": (".eventing", "deltate"),
    "denot": (".annotating", "denot"),
    "dumps": (".coring", "dumps"),
    "exchange": (".eventing", "exchange"),
    "exchept": (".eventing", "exchept"),
    "incept": (".eventing", "incept"),
    "interact": (".eventing", "interact"),
    "loadEvent": (".eventing", "loadEvent"),
    "loads": (".coring", "loads"),
    "messagize": (".eventing", "messagize"),
    "prod": (".eventing", "prod"),
    "query": (".eventing", "query"),
    "receipt": (".eventing", "receipt"),
    "reply": (".eventing", "reply"),
    "rotate": (".eventing", "rotate"),
    "simple": (".eventing", "simple"),
    "sizeify": (".coring", "sizeify"),
    "state": (".eventing", "state"),
    "validateSigs": (".eventing", "validateSigs"),
    "verifySigs": (".eventing", "verifySigs"),
}

__all__ = [*_MODULES, *_EXPORTS]


def __getattr__(name):
    if name in _MODULES:
        module = importlib.import_module(_MODULES[name], __name__)
        globals()[name] = module
        return module

    if name in _EXPORTS:
        module_name, export_name = _EXPORTS[name]
        module = importlib.import_module(module_name, __name__)
        value = getattr(module, export_name)
        globals()[name] = value
        return value

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals()) | set(__all__))
